version: '3'

networks:
  wordpress:

volumes:
  db-data:

services:

  apache2:
    build: apache2
    restart: always
    ports:
      - "80:80"
    links:
     - mysql
    environment:
      - MYSQL_DATABASE=wp_install
    networks:
      - wordpress

  mysql:
    build: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=wp_install
    networks:
      - wordpress
    volumes:
      - db-data:/var/lib/mysql