version: '3'

networks:
  wordpress:

volumes:
  db-data:

services:

  apache2:
    build:
      context: .
    env_file:
      - .env
    restart: always
    ports:
      - "80:80"
    networks:
      - wordpress

  mysql:
    image: mysql:5.7
    env_file:
      - .env
    restart: always
    networks:
      - wordpress
    volumes:
      - db-data:/var/lib/mysql