version: '3'

networks:
  wordpress:

volumes:
  db-data:

services:

  apache2:
    build:
      context: .
    restart: always
    ports:
      - "80:80"
    environment:
      - MYSQL_DATABASE=wp_install
    networks:
      - wordpress

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=wp_install
    networks:
      - wordpress
    volumes:
      - db-data:/var/lib/mysql