version: '3'

services:

  apache2:
    build: apache2
    restart: always
    ports:
      - "80:80"
    links:
     - mysql
    environment:
      - MYSQL_DATABASE=wp_install

  mysql:
    build: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=wp_install